### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sarnthil** [evanmiltenburg/dm-graphs#1]
What license is this repository under? I would like to use it and want to be on the safe side.

**Comment by evanmiltenburg** [comment]
Thanks for the question, I just added the Apache license to the repository.

The Gephi plugin from the Oxford Internet Institute uses Sigma.js ([which is MIT licensed](https://github.com/jacomyal/sigma.js/blob/master/LICENSE.txt)) and [is itself licensed under GNU GPL v3](http://blogs.oii.ox.ac.uk/vis/2012/11/15/build-your-own-interactive-network/). Of course you don't have to use this plugin, but just in case :)

**Comment by sarnthil** [comment]
Cool :), thank you for the quick reply! 👍

**Comment by evanmiltenburg** [comment]
Let me know if you'd like me to link to your results! Always nice to have examples of how the code could be used.
